#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightRear,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "serialCortexTask.h"


task main()
{
	startTask(serialRxTask);
	while(vars[2] <= 255)
	{
		motor[leftFront] = 63;
		motor[rightFront] = 63;
		motor[leftRear] = 63;
		motor[rightRear] = 63;
	}



}
